export interface BannerData {
  // Product
  productName: string;
  productImageUrl: string | null;   // real uploaded photo
  // Copy (generated by Claude)
  headline: string;
  subheadline?: string;
  bodyText?: string;
  cta: string;
  bullets: string[];
  // Offer
  priceSale?: string;
  priceOriginal?: string;
  saleLabel?: string;
  // Style
  primaryColor: string;    // e.g. "#FF6B35"
  secondaryColor: string;  // e.g. "#1C1C26"
  accentColor: string;     // e.g. "#FFFFFF"
  bgColor: string;
  // Section
  sectionType: string;
  // Computed
  country?: string;
}

export interface BannerTemplate {
  id: string;
  sectionType: string;
  name: string;
  component: React.ComponentType<{ data: BannerData }>;
}
